Repository DUNE/dune-tms, pull requests merged in 2024-09, with the labels that each got.

#144 unspacked spack
  setup_FNAL.sh
Labels: bug

#133 Feature/combine sd
  scripts/Truth/plot_multiple_truth_signed_distances.py
Labels: enhancement

#135 125 potential problem with tracks in clusters
  app/ConvertToTMSTree.cpp
  config/TMS_Default_Config.toml
  scripts/Reco/draw_spill_3D_projections.py
  scripts/Reco/geometry_comparison.py
  scripts/Reco/performance_reco.py
  setup.sh
  src/Makefile
  src/Material.h
  src/TMS_Bar.cpp
  src/TMS_DBScan.h
  src/TMS_Event.cpp
  src/TMS_Geom.h
  src/TMS_Hit.h
  src/TMS_Kalman.cpp
  src/TMS_Kalman.h
  src/TMS_Manager.cpp
  src/TMS_Manager.h
  src/TMS_Reco.cpp
  src/TMS_Reco.h
  src/TMS_Track.h
  src/TMS_TreeWriter.cpp
  src/TMS_TreeWriter.h
Labels: bug, enhancement

#154 Feature/mdolce muon efficiency
  scripts/Truth/plot_multiple_truth_efficiencies.py
  scripts/Truth/sign_distance_efficiency_vs_muon_true_ke.py
Labels: enhancement
